<?php
namespace backend\module\home\controllers;

use common\models\Exam;
use yii\db\Exception;
use yii\web\Controller;
use yii\common\models\User;
use yii\web\Response;
use yii\web\Request;
use yii\db\Query;
use yii\db\ActiveRecord;
use yii\helpers\ArrayHelper;
use yii\filters\Cors;
use yii\behaviors\TimestampBehavior;
use backend\module\home\controllers\IndexController;
use yii\data\Pagination;
header("Access-Control-Allow-Origin: *");
file_get_contents("php://input");
/**
 * Default controller for the `home` module
 */

class UserController extends Controller
{
    public function actionIndex()
    {
        return "user"; // TODO: Change the autogenerated stub
    }
    public function PasswordDecry($password,$encryptedData="zhouqing")
    {
        return \Yii::$app->getSecurity()->decryptByPassword(base64_decode($password),$encryptedData);
    }
    public function PasswordEncry($password,$encryptedData="zhouqing")
    {
        $en = \Yii::$app->getSecurity()->encryptByPassword($password,$encryptedData);
        return base64_encode($en);
    }
//    查找角色
    public function Queryrole($id)
    {
        return (new Query())
            ->select('*')
            ->from('role')
            ->where(['id'=>$id])
            ->andWhere(['status'=>1])
            ->one();
    }
//    用户列表
    public function actionQuery()
    {
        $request = \Yii::$app->request;
        $flag = $request->post('flag');
        if($flag==1)
        {
            $query = (new Query())
                ->select('*')
                ->from('user')
                ->all();
            $list = [];
            for($i=0;$i<count($query);$i++)
            {
                $list[$i]['id']=$query[$i]['id'];
                $list[$i]['no']=$query[$i]['no'];
                $list[$i]['username']=$query[$i]['username'];
                $list[$i]['password']=$this->PasswordDecry($query[$i]['password']);
                $list[$i]['role']=$this->Queryrole($query[$i]['role'])['name'];
                $list[$i]['status']=$query[$i]['status'];
                $list[$i]['email']=$query[$i]['email'];
            }
            return array('data'=>$list,'msg'=>'全部用户信息');
        }
    }
//   删除用户
    public function actionDeleteuser()
    {
       $request = \Yii::$app->request;
       $id = $request->post('id');
       $flag = $request->post('flag');
       if($flag==1)
       {
           $deleteU = \Yii::$app->db->createCommand()->update('user',['status'=>0],['id'=>$id])->execute();
       }
       else if($flag==2)
       {
           $deleteU = \Yii::$app->db->createCommand()->update('user',['status'=>1],['id'=>$id])->execute();
       }
       else
       {
           $deleteU = \Yii::$app->db->createCommand()->delete('user',['id'=>$id])->execute();

       }
        if($deleteU)
        {
            return array('data'=>$deleteU,'msg'=>'成功');
        }
        else
        {
            return array('data'=>$deleteU,'msg'=>'失败');
        }

    }
//    用户身份列表
    public function actionGetrole()
    {
        $query = (new Query())
            ->select('*')
            ->from('role')
            ->where(['status'=>1])
            ->all();
        return array('data'=>$query,'msg'=>'用户角色');
    }
//    用户id
    public function ID()
    {
        return (new Query())
            ->select('*')
            ->from('user')
            ->max('id')+1;
    }
//    默认密码设置
    public function defaultPass($role)
    {
        switch ($role)
        {
            case 1:{
                $pass='root@123';
                break;
            }
            default:
            {
                $pass = 'zhou@123';
                break;
            }
        }
        $pass = $this->PasswordEncry($pass);
        return $pass;
    }
//    添加用户
    public function actionAdduser()
    {
        $request = \Yii::$app->request;
        $no = $request->post('no');
        $name = $request->post('name');
        $role = $request->post('role');
        $query = (new Query())
            ->select('*')
            ->from('user')
            ->where(['no'=>$no])
            ->andWhere(['role'=>$role])
            ->one();
        if($query)
        {
            return array('data'=>$query,'msg'=>$no.'已添加');
        }
        else
        {
            $insertU = \Yii::$app->db->createCommand()->insert('user',
                array('id'=>$this->ID(),'no'=>$no,'username'=>$name,'role'=>$role,'password'=>$this->defaultPass($role),'status'=>1,'email'=>'')
            )->execute();
            if($insertU)
            {
                return array('data'=>[],'msg'=>'添加成功');
            }
            else
            {
                return array('data'=>[],'msg'=>'添加失败');
            }
        }
    }
//    获得用户表，但是不能有其本人
    public function actionUserlist()
    {
        $request = \Yii::$app->request;
        $id = $request->post('id');
        $query = (new Query())
            ->select('*')
            ->from('user')
            ->where(['<>','id',$id])
            ->andWhere(['status'=>1])
            ->all();
        return array('data'=>$query,'msg'=>'除了本人以外的用户');
    }

}